[package]
name = "rues"
version = "0.1.0"
edition = "2021"

[dependencies]
mdns-sd = { version = "0.2" }
reqwest = { version = "0.11", features = [ "json", "native-tls" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0" }
url = { version = "2.2" }

[dev-dependencies]
tokio = { version = "1.15", features = [ "rt-multi-thread", "macros" ] }